# permissions for end users to view accesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-operator
    app.kubernetes.io/managed-by: kustomize
  name: access-viewer-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accesses/status
  verbs:
  - get
