# permissions for end users to edit accesstunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-operator
    app.kubernetes.io/managed-by: kustomize
  name: accesstunnel-editor-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accesstunnels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accesstunnels/status
  verbs:
  - get
