#!/usr/bin/env python3
"""Sync RBAC from config/rbac/ into the cloudflare-operator Helm chart.

Two tasks:
1. Sync the manager ClusterRole rules from config/rbac/role.yaml into
   charts/cloudflare-operator/templates/rbac.yaml (rules: block only).
2. Regenerate charts/cloudflare-operator/templates/rbac-helpers.yaml from
   the editor/viewer/admin role files, adding Helm template directives.

Requires: yq (https://github.com/mikefarah/yq) — pre-installed on
ubuntu-latest GitHub Actions runners and available via most package managers.
"""
import re
import subprocess
import sys
from pathlib import Path

ROLE_SRC = "config/rbac/role.yaml"
RBAC_TMPL = "charts/cloudflare-operator/templates/rbac.yaml"
HELPERS_TMPL = "charts/cloudflare-operator/templates/rbac-helpers.yaml"

# Helper roles to sync: (source file, name suffix, comment)
HELPER_ROLES = [
    ("config/rbac/accesstunnel_editor_role.yaml",   "accesstunnel-editor-role",   "permissions for end users to edit accesstunnels."),
    ("config/rbac/accesstunnel_viewer_role.yaml",   "accesstunnel-viewer-role",   "permissions for end users to view accesstunnels."),
    ("config/rbac/clustertunnel_admin_role.yaml",   "clustertunnel-admin-role",   "Grants full permissions ('*') over clustertunnels."),
    ("config/rbac/clustertunnel_editor_role.yaml",  "clustertunnel-editor-role",  "permissions for end users to edit clustertunnels."),
    ("config/rbac/clustertunnel_viewer_role.yaml",  "clustertunnel-viewer-role",  "permissions for end users to view clustertunnels."),
    ("config/rbac/tunnel_admin_role.yaml",          "tunnel-admin-role",          "Grants full permissions ('*') over tunnels."),
    ("config/rbac/tunnel_editor_role.yaml",         "tunnel-editor-role",         "permissions for end users to edit tunnels."),
    ("config/rbac/tunnel_viewer_role.yaml",         "tunnel-viewer-role",         "permissions for end users to view tunnels."),
    ("config/rbac/tunnelbinding_editor_role.yaml",  "tunnelbinding-editor-role",  "permissions for end users to edit tunnelbindings."),
    ("config/rbac/tunnelbinding_viewer_role.yaml",  "tunnelbinding-viewer-role",  "permissions for end users to view tunnelbindings."),
]

HELM_NAME   = '{{ include "cloudflare-operator.fullname" . }}'
HELM_LABELS = '    {{- include "cloudflare-operator.labels" . | nindent 4 }}'


def yq(expr, path):
    return subprocess.check_output(["yq", expr, path]).decode().rstrip("\n")


def rules_indented(src):
    raw = yq(".rules", src)
    if not raw or raw == "null":
        print(f"ERROR: could not extract rules from {src}", file=sys.stderr)
        sys.exit(1)
    return "\n".join("  " + line if line else "" for line in raw.split("\n"))


# ── 1. Sync manager ClusterRole rules into rbac.yaml ─────────────────────────

with open(RBAC_TMPL) as f:
    content = f.read()

new_content, n = re.subn(
    r"(rules:\n)((?:(?!---).)*?)(---)",
    "rules:\n" + rules_indented(ROLE_SRC) + "\n---",
    content,
    count=1,
    flags=re.DOTALL,
)

if n == 0:
    print(f"ERROR: could not find rules block in {RBAC_TMPL}", file=sys.stderr)
    sys.exit(1)

with open(RBAC_TMPL, "w") as f:
    f.write(new_content)

print(f"helm-sync-rbac: synced manager ClusterRole rules from {ROLE_SRC}")


# ── 2. Regenerate rbac-helpers.yaml ──────────────────────────────────────────

def build_helper_doc(src, name_suffix, comment):
    rules_raw = yq(".rules", src)
    if not rules_raw or rules_raw == "null":
        print(f"ERROR: could not extract rules from {src}", file=sys.stderr)
        sys.exit(1)
    rules_block = "\n".join("  " + line if line else "" for line in rules_raw.split("\n"))
    return f"""\
---
# {comment}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {HELM_NAME}-{name_suffix}
  labels:
{HELM_LABELS}
rules:
{rules_block}"""


docs = "\n".join(build_helper_doc(src, suffix, comment) for src, suffix, comment in HELPER_ROLES)

helpers_content = f"""\
{{{{- if .Values.rbac.installHelperRoles }}}}
# Helper ClusterRoles for end-user access to cloudflare-operator CRDs.
# Not used by the operator itself. Auto-generated by hack/helm-sync-rbac.py.
{docs}
{{{{- end }}}}
"""

with open(HELPERS_TMPL, "w") as f:
    f.write(helpers_content)

print(f"helm-sync-rbac: regenerated {HELPERS_TMPL} ({len(HELPER_ROLES)} helper roles)")
