apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ include "cloudflare-operator.namespace" . }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/component: metrics
    {{- include "cloudflare-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager
