apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare-operator.fullname" . }}-webhook-service
  namespace: {{ include "cloudflare-operator.namespace" . }}
  labels:
    {{- include "cloudflare-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
