image:
  repository: adyanth/cloudflare-operator
  pullPolicy: IfNotPresent
  tag: "" # Overrides the image tag whose default is the chart appVersion.

imagePullSecrets: []
nameOverride: "" # This is to override the chart name.
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
   capabilities:
     drop:
     - ALL
   readOnlyRootFilesystem: true
   allowPriviledgeEscalation: false
#   runAsNonRoot: true
#   runAsUser: 1000

resources:
   limits:
     cpu: 200m
     memory: 200Mi
   requests:
     cpu: 100m
     memory: 100Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
                - arm64
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
command:
  - /manager
args:
  - --metrics-bind-address=:8443
  - --leader-elect
  - --health-probe-bind-address=:8081

dashboard:
  enabled: true

service:
  type: ClusterIP
  port: 8443
