name: test

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go 1.24.0
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0
      - name: Test
        run: make test
