name: test

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Test
        run: make test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: cover.out
  code_coverage:
    name: "Code coverage report"
    if: github.event.pull_request.head.repo.full_name == github.repository # run only when the PR’s branch lives in this repo
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents:      read
      actions:       read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: fgrosse/go-coverage-report@v1.1.1
        with:
          coverage-artifact-name: "code-coverage"
          coverage-file-name: "cover.out"
